# Generated by Django 6.0 on 2026-01-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
