# Generated by Django 6.0 on 2026-01-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='price_try',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
