# Generated by Django 6.0 on 2026-01-06 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_grade_subject_topictemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topictemplate',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='topictemplate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.topictemplate'),
        ),
    ]
