# Generated by Django 6.0 on 2026-01-11 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_topiccontent_topicquestion_studenttopicprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('wrong_count_total', models.PositiveIntegerField(default=0)),
                ('last_wrong_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='content.topictemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.reviewitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='reviewitem',
            index=models.Index(fields=['user', 'next_review_at'], name='content_rev_user_id_927435_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewitem',
            index=models.Index(fields=['user', 'is_active'], name='content_rev_user_id_7f676e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewitem',
            unique_together={('user', 'topic')},
        ),
    ]
